name: tcg_collector
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6

  # --- State Management ---
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # --- Datenbank (Fix auf 2.19.0) ---
  drift: 2.19.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.9.0

  # --- Netzwerk ---
  dio: ^5.4.1
  cached_network_image: ^3.3.1
  google_fonts: ^4.0.3

  # --- Sonstiges ---
  pokemon_tcg: ^1.0.1
  device_preview: ^1.2.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # --- Code Generatoren ---
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
  
  # Muss exakt zur drift Version oben passen:
  drift_dev: 2.19.0

flutter:
  uses-material-design: true